/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mongodb.hibernate;

/**
 * Temporary class only for project onboarding CI building purpose.
 * <p>
 * Generated by 'gradle init' task.
 * <p>
 * Will be deleted once project onboarding is done.
 */
public class OnlyForTest {
    public boolean someMethod() {
        return true;
    }
}
