/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mongodb.hibernate;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OnlyForTestTest {
    @Test void someMethodReturnsTrue() {
        OnlyForTest classUnderTest = new OnlyForTest();
        assertTrue(classUnderTest.someMethod(), "someMethod should return 'true'");
    }
}
